### ISSUE TITLE
lonestar-cpu-inputs.tar.xz is re-extracted every build

### ISSUE THREAD

**Issue by tbennun** [IntelligentSoftwareSystems/Galois#1]
Hi there,

Every time I run `make`, the target 'input' somehow does not recognize that the file has been unpacked, and I get this output:
```
[  0%] Unpacking lonestar-cpu-inputs.tar.xz
```
which takes a while. I'm using the release-4.0 branch (which seems to be in sync with master).

**Comment by amberhassaan** [comment]
Hi Tal,
Thanks for bringing this to attention. It is indeed a problem and shouldn't be happening. I'll look into it and post an update here once it's fixed.

**Comment by amberhassaan** [comment]
The repeated untar-ing of inputs is fixed now. I've updated both master and release branches. 
Thanks.
