### ISSUE TITLE
Fix CMake (3.17) warnings

### ISSUE THREAD

**Issue by roshandathathri** [IntelligentSoftwareSystems/Galois#106]
CMake Warning (dev) at /org/centers/cdgc/sw/miniconda/envs/cmake-3.17/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /org/centers/cdgc/sw/miniconda/envs/cmake-3.17/share/cmake-3.17/Modules/FindCUDA.cmake:593 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CUDA_SEPARABLE_COMPILATION'.
Call Stack (most recent call first):
  CMakeLists.txt:208 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /org/centers/cdgc/sw/miniconda/envs/cmake-3.17/share/cmake-3.17/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    m

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  cmake/Modules/llvm-extras.cmake:39 (check_include_file)
  libllvm/CMakeLists.txt:16 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by insertinterestingnamehere** [comment]
Just to add a little more to this, we've done an extensive cleanup of warnings in our C++ files, but there are also a handful of CMake warnings we should probably address.

**Comment by ddn0** [comment]
I haven't seen these errors recently and I know that at least

> CMake Warning (dev) at /org/centers/cdgc/sw/miniconda/envs/cmake-3.17/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known. Please enable at least one language before
including GNUInstallDirs.

is already fixed on master (post the recent Katana merge).

@roshandathathri could you confirm that you are seeing warnings even now?

**Comment by insertinterestingnamehere** [comment]
These appear fixed to me as well. Waiting for confirmation from @roshandathathri.

**Comment by roshandathathri** [comment]
Yes, these are fixed. But I cannot build distributed GPU code due to CMake Errors. More on that later.
