### ISSUE TITLE
Removal in MorphGraph is buggy

### ISSUE THREAD

**Issue by yishanlu** [IntelligentSoftwareSystems/Galois#115]
`galois::graphs::MorphGraph` is buggy at edge/node removal when the graph is instantiated directed and tracking incoming/outgoing edges at the same time. Need to trace down the root cause and fix it.

`galois::graphs::First_SepInOut_Graph` in experimental features fixed the issue by separating incoming edges and outgoing edges to different vectors. We can move this to production code (probably with renaming the class).

**Comment by yishanlu** [comment]
`galois::graphs::First_SepInOut_Graph` should be moved from libgalois/experimental/include/galois/graphs/First_SepInOut_Graph.h to libgalois/include/galois/graphs/Morph_SepInOut_Graph.h.

We can think of another name for the class/header.

**Comment by yishanlu** [comment]
This is due to the misuse of the API. When a user tries to remove an incoming edge, he or she needs to find the incoming edge iterator first; for `MorphGraph.findInEdge(src,dst)`, the incoming edge should be found in `dst` and compared to `MorphGraph.in_edge_end(dst)`. This needs to be documented.

Confirmed with `libgalois/test/morphgraph-removal.cpp` that the implementation is not buggy. The test is now available in our private master branch.

**Comment by insertinterestingnamehere** [comment]
Just pushed this. Thank you for tracking this down!
