### ISSUE TITLE
Remove ConditionalReducible

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#121]
Compile-time removal of reduction operations seems more naturally formulated as a Stat rather than as a Reducible. Either the functionality is part of the algorithm (Reducible) or it is an observability metric (Stat).

The only user of ConditionalReducible is Between Centrality (async).

It seems better to improve Stats to match the desired use case rather than introducing more Reducible types.

Thoughts @l-hoang ?

**Comment by l-hoang** [comment]
Agreed.

We have a ConditionalStatTimer, for instance. Something similar can be implemented for other Stats as well.
