### ISSUE TITLE
RFC: Move from pure Doxygen to Sphinx

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#134]
In a world where there is a Python interface for Galois, it would be nice if the C++ and Python API documentation in the same form and interlinked between each other.

A common Python documentation tool is Sphinx and there appears to be a way to import Doxygen output into it: https://exhale.readthedocs.io (based on https://breathe.readthedocs.io)

The proposal is to use Sphinx as the main container for Galois documentation (APIs, tutorials, etc.) and import Doxygen-extracted C++ material via exhale/breathe.

An alternative would be to continue using Doxygen as the main container for documentation. In which case, Python APIs would need to be extracted and imported into Doxygen.

Example Sphinx themes: https://sphinx-themes.org/

Related but separate proposal: move the benchmark/application descriptions into the same format.

**Comment by insertinterestingnamehere** [comment]
BTW, I briefly looked at using Breathe for similar reasons when working on libdynd and never got it working there. Now they are using breathe in https://github.com/xtensor-stack/xtensor now though so that can be used as a minimal working example.
