### ISSUE TITLE
Installing LLVM (>= 7.0 with RTTI support)

### ISSUE THREAD

**Issue by GeoBK** [IntelligentSoftwareSystems/Galois#135]
I was trying to get the Lonestar code to work on my system but whenever I run CMake its erroring out on me saying that "LLVM 7 or greater is required."
I had installed llvm by running sudo apt install llvm - but on running llvm-config --version it says that I have installed version 6.0.0 
Is there a simple way to install the dependencies for this project on an Ubuntu 18.04 system?

**Comment by ddn0** [comment]
This is how our CI installs Galois on an Ubuntu 18.04 machine:

  https://github.com/IntelligentSoftwareSystems/Galois/blob/master/.circleci/config.yml#L61

An `apt-get install llvm-7-dev` should do the trick.
