### ISSUE TITLE
K-Truss: support reading unweighted graphs

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#141]
K-Truss needs edge data while running but it can take input graphs without edge data. We should probably provide a general capability in `readGraph` to indicate different input and output graph formats, e.g., `readGraph<InputEdgeTy...>(outputGraph)`.

**Comment by l-hoang** [comment]
I actually had to implement something like this for GaloisBLAS; let me see what I did there and I'll get back to you.

**Comment by l-hoang** [comment]
Putting the responsibility on this to @nicelhc13; he knows exactly what this problem is since we were involved in GaloisBLAS together.

**Comment by nicelhc13** [comment]
That is a cool idea. Yes I can reuse Loc's codes. I'll keep you updated.

**Comment by nicelhc13** [comment]
I have one question on this task.
I found that the current Galois always allocate edge data array even though the edge type is void.
The current Loc's codes on GaloisBLAS just set an empty value to the edge data array.

I would like to avoid the allocations from the execution path by passing template parameters.
Do you guys agree with that? or do you guys have any idea or feedback on this?

**Comment by l-hoang** [comment]
For ktruss in particular you need to allocate that array.

This use case is for when the graph needs edge data but the .gr file on disk doesn't have edge data, so you *want* to allocate something for it.

**Comment by nicelhc13** [comment]
Thank you for clarification, Loc. Then, I can use your codes.
But I think the above issue would be still valid. Depending on applications, avoiding edge data arrays seems useful though I have to look into more if Galois already supports this or not.

**Comment by nicelhc13** [comment]
I added this functionality through the following commits: 1a4023889f6126f6173862baab0c9bc8fd8262b3 b4eedbbfd357050a142b50b64d37c41255132d57

Thank you.
