### ISSUE TITLE
Get dist tests running on CI

### ISSUE THREAD

**Issue by l-hoang** [IntelligentSoftwareSystems/Galois#146]
Title is self explanatory.

**Comment by ddn0** [comment]
I don't know if you want to pull this in as part of the basic work of getting dist tests working, but it looks like most of the dist tests can verify their output with respect to a pre-computed output:

  https://github.com/IntelligentSoftwareSystems/Galois/blob/master/lonestardist/CMakeLists.txt#L88

I would be nice to get the same coverage in CI.

**Comment by gurbinder533** [comment]
It does make sense to include it into CI testing as there are more moving parts such as partitioning policies, etc in the distributed setting which should be tested with baseline verified output.
