### ISSUE TITLE
lonestardist/tc doesn't build

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#148]

**Comment by l-hoang** [comment]
Doesn't build as in "error" or doesn't build as it's not being picked up for build?

At the moment it should only build for GPU configurations as there isn't a CPU implementation. That implementation is something on me to do soon.

**Comment by ddn0** [comment]
```
[  9%] Building CUDA object lonestardist/tc/CMakeFiles/tc_cuda.dir/tc_cuda.cu.o
/home/ddn/w/katana/lonestardist/tc/tc_cuda.cu:9:10: fatal error: kernels/reduce.cuh: No such file or directory
 #include "kernels/reduce.cuh"
          ^~~~~~~~~~~~~~~~~~~~
```

**Comment by l-hoang** [comment]
@vishweshjatala

**Comment by vishweshjatala** [comment]
Fixed and verified locally.  Created a pull request 
https://github.com/IntelligentSoftwareSystems/Galois/pull/149
