### ISSUE TITLE
Rename __GALOIS_HET_CUDA__

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#153]
Tangential to this, but we generally should avoid underscore prefixes on preprocessor symbols since that class of names is supposed to be reserved for the compiler. https://stackoverflow.com/a/228797 has details.

@insertinterestingnamehere

https://github.com/IntelligentSoftwareSystems/Galois/pull/145

**Comment by roshandathathri** [comment]
+1 

We should rename all ___X preprocessor symbols we use to GALOIS_X

**Comment by roshandathathri** [comment]
Fixed in PR 199
