### ISSUE TITLE
Rename ENABLE_{DIST,HETERO}_GALOIS to GALOIS_ENABLE_... in cmake files

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#163]
This follows the popular convention of prefixing all unnamespaced symbols with the project name and also appears to be the common pattern in other CMake-based projects.

Additionally, we might consider adding `GALOIS_` to any bare configuration parameters like `USE_XYZ`. Though, we might considering delaying this action until we audit/winnow the remaining options to ones we think are necessary.

**Comment by roshandathathri** [comment]
+1 

I was just thinking about this yesterday.

**Comment by roshandathathri** [comment]
Fixed in PR 199
