### ISSUE TITLE
Undefined behavior/memory leaks in distributed apps

### ISSUE THREAD

**Issue by l-hoang** [IntelligentSoftwareSystems/Galois#174]
As pointed out in PR #165, dist apps have undefined behavior + mem leaks for multi-process execution + bc_mr.

**Comment by insertinterestingnamehere** [comment]
Nice to have for the 6.0 release, but not required.

**Comment by roshandathathri** [comment]
Everything other than bc_mr has been fixed in #281, so I'm transferring this to @bozhiyou

**Comment by bozhiyou** [comment]
> Everything other than bc_mr has been fixed in #281, so I'm transferring this to @bozhiyou

Fixing this in pr #293, but not sure if it's the essential reason since other dist-apps with the same issue I found there does not fail the tests. Any thoughts?

**Comment by bozhiyou** [comment]
#293 merged. Closing this.
