### ISSUE TITLE
Consistent Lonestar App Naming

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#177]
There's little correspondence right now between the lonestar distributed app names and the lonestar shared memory app names. bfs and sssp are the same, but then connectedcomponents is cc in distributed and betweennesscentrality is bc in distributed. More broadly, are we using acronyms everywhere? We're inconsistent about that right now. What about capitalization?

**Comment by l-hoang** [comment]
I prefer the shorter names, but I'm fine with whichever.

I do agree that they should be consistent.

**Comment by insertinterestingnamehere** [comment]
Yah, my preference is slightly for the longer names since it'll be clearer to people who aren't super-familiar with the project, but I really just care that we be consistent. I'm leaving this alone in the folder reorganization though until we can figure out what we want to do.

**Comment by roshandathathri** [comment]
SGD in distributed should be renamed to matrixcompletion as well.

**Comment by roshandathathri** [comment]
@nicelhc13 this is done, right?
