### ISSUE TITLE
Memory Leaks in SPRoute

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#179]
SPRoute fails when running with the address sanitizer because there are various memory leaks. I've fixed a few of them in https://github.com/IntelligentSoftwareSystems/Galois/pull/178, but a handful remain. To reproduce them, configure with
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DGALOIS_USE_SANITIZER="Address;Undefined" ..
```

**Comment by Michael-JY-He** [comment]
After this cmake, run SPRoute as normal?

**Comment by insertinterestingnamehere** [comment]
Yep. Thanks for looking into it!

**Comment by Michael-JY-He** [comment]
Fixed. Please check.

**Comment by insertinterestingnamehere** [comment]
Confirmed fixed. Thank you!
