### ISSUE TITLE
Memory Leak in Bipart

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#184]
The sanitizer build is failing with the bipart tests. (See https://app.circleci.com/pipelines/github/IntelligentSoftwareSystems/Galois/367/workflows/8c72e0e6-b3d5-466c-9479-65c4b0b36edb/jobs/7453).

To reproduce the error, configure with
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DGALOIS_USE_SANITIZER="Address;Undefined" ..
```

**Comment by Breakinbad** [comment]
I don't know why it fails :( I tried without test on the same input it
passes. There was a memory leak issue which I fixed but still tests fails
:((

**Comment by Breakinbad** [comment]
Fixed!

**Comment by insertinterestingnamehere** [comment]
Great, thanks for fixing that! I'll re-enable the test in CI.
