### ISSUE TITLE
Compiler Bug in Gcc 7.2 C++17 Support

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#185]
Currently, when building with gcc 7.2 or 7.1 we get a bunch of errors of the form `error: uninitialized variable ‘thing’ in ‘constexpr’ function` in many of the Lonestar apps. As far as I can tell, this is an example of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80935.

Given that there's not an obvious workaround other than dropping C++17 or dropping our use of lambdas for parallel loops in the Lonestar apps, I propose we require gcc 7.3 or higher instead of just gcc 7. Usually I don't worry much about requiring newer minor release versions, however on our development machines, gcc 7.2 is the only gcc version in the gcc 7 series we currently have set up. It doesn't look like this will cause any issues with any of the major Linux distros though. In addition, it's very likely that we will be updating the OS setup on our development machines soon anyway.

Is requiring gcc 7.3 or later okay with everyone?

**Comment by roshandathathri** [comment]
I wouldn't mind but Stampede only has gcc 7.1 (with MPI and boost support). I wouldn't want to make it hard for us to use Galois on Stampede or any other cluster we use. 

What are our other options?

**Comment by l-hoang** [comment]
Stampede2 also has gcc 7.3 and 9.1, but 9.1 if I recall had issues because it doesn't have a compatible boost version that we can use.

**Comment by roshandathathri** [comment]
I was talking about Stampede2 only. Neither gcc 7.3 nor gcc 9.1 have compatible MPI or boost modules.

**Comment by insertinterestingnamehere** [comment]
I'm not sure there are other good options. I can hack on it a bit more and try to find a workaround, but, looking at the bug report, a reliable workaround seems unlikely. Note, however, that this is only in the Lonestar apps, not the core library.

**Comment by insertinterestingnamehere** [comment]
Note: the gcc 7.1 binaries they have should work fine without any modification with binaries built with the gcc 7.3 compiler. I don't know if they've configured their modules to be aware of that fact though.

**Comment by roshandathathri** [comment]
> Note: the gcc 7.1 binaries they have should work fine without any modification with binaries built with the gcc 7.3 compiler. I don't know if they've configured their modules to be aware of that fact though.

No, they haven't. The modules are not available for later versions as of now.

**Comment by insertinterestingnamehere** [comment]
Can we file a ticket with them to make that happen? The last time gcc broke C++ abi compatibility was between the 4.9 and 5.0 releases, so whatever binaries they already have for 7.1 should be fine with 7.3 and 9.1.

**Comment by insertinterestingnamehere** [comment]
There was a Fortran ABI break between releases 7 and 8, so whether or not mpi can be re-used for gcc 9 will depend on whether it needs libgfortran. My point still stands about gcc/gfortran 7.3 though.

**Comment by roshandathathri** [comment]
Loc will check with them about it.

**Comment by insertinterestingnamehere** [comment]
Thanks. I'll double check that this can't be fixed. I remember building with our gcc 7 fairly recently so maybe there's still some way to get it working.

**Comment by l-hoang** [comment]
Thanks to Roshan we have a list of problematic apps with this bug for shared memory:

bipartite-mcm
preflow-push
SProute

Note that Stampede2 folks still haven't resolved this; we'll discuss steps moving forward tomorrow.

**Comment by roshandathathri** [comment]
> we get a bunch of errors of the form `error: uninitialized variable ‘thing’ in ‘constexpr’ function` in many of the Lonestar apps

I see this error only for three apps - bipartite-mcm, preflow-push, and SPRoute. We can go with one of these approaches:
(1) State (in the README and wherever else) that the minimum required gcc is 7.0 with the caveat that the apps bipartite-mcm, preflow-push, and SPRoute require gcc 7.3 or above.
(2) State (in the README and wherever else) that the minimum required gcc is 7.3 with the caveat that everything except the apps bipartite-mcm, preflow-push, and SPRoute require gcc 7.0 or above.
(3) Modify those apps to not use the buggy feature if possible.

I'm fine with any of those approaches.

**Comment by l-hoang** [comment]
I think (3) might be the most clean way of doing this as it requires no extra work from a user if we can get it going.
