### ISSUE TITLE
RFC: Remove HPCTK

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#186]
If we are only concerned with Linux profiling, `perf` gives us reasonable support for performance counters though not confined to an application-specific region, which is probably preferable for end-to-end performance debugging though. This is probably a good replacement for any PAPI use cases.

The HPCTK support doesn't seem too deep. Does anyone use this?

VTune has reasonable profiling tools but do we need application-specific timing regions, which requires linking to their library?

**Comment by insertinterestingnamehere** [comment]
IIRC, @amberhassaan was the last one to work on this.

**Comment by roshandathathri** [comment]
Yes, we would need application-specific timing regions. That has been useful in the past. 

I have not used HPCTK but I have used both VTune and PAPI. I think VTune is sufficient but both have their use cases.

**Comment by ddn0** [comment]
> I have not used HPCTK but I have used both VTune and PAPI. I think VTune is sufficient but both have their use cases.

The reason I'm suggesting `perf` is that it multiplexes performance counters for you and has an extensive ecosystem of tools around it. PAPI is pretty low-level.

A thought: you might be able to get application-defined region-like behavior by reorganizing the code a bit and extracting it post-facto from recorded stack traces from any sampling based profiler.

Anyway, the reason I would like to move away from compile-time profiling configuration is that it is hard to turn on in a deployed setting. I'd be much happier with some interface that can always enabled for instance.

I think we can remove PAPI and HPCTK direct linking options at least.

**Comment by roshandathathri** [comment]
I'm fine with that. 

It would be good to have something for a deployed setting. Nevertheless, I would prefer to keep compile-time profiling options as well.

**Comment by amberhassaan** [comment]
PAPI and Vtune have served different needs for us. Vtune for analyzing bottlenecks as we scale to multiple threads. PAPI for more zoomed in region analysis. 

I think we definitely need region specific profiling tools. I like perf and if someone knows how to interact with perf from an application, then we can develop an API on top of that in Galois. I tried looking into it briefly and didn't find a good library that uses perf.

**Comment by roshandathathri** [comment]
I agree with Amber. Is there a strong reason to remove PAPI? VTune is not a replacement for PAPI because they serve different purposes.

**Comment by yishanlu** [comment]
I agree with Roshan. VTune is only applicable to Intel machines, and we do not have the support for PERF in placer right now. A region-specific way of profiling is valuable.

**Comment by ddn0** [comment]
PAPI is just a library to read performance counters. So the question is really whether we implement, maintain and support the extra work to turn performance counters into useful information.

Some of that work currently exists in the codebase but is specific to Galois and limited in capability. And I agree that it is useful in its current form; I was the one who added PAPI support to begin with so many years ago. I also believe you can get the same effect just by using commonly available tools, and tools like `perf` are much more flexible and more useful than what we have in Galois.

If someone asked me to diagnose a performance problem now, I'd point them to one of those tools. And as a side benefit, you get to learn a tool that you can apply to any application. So my reason for wanting to remove PAPI support is simple. If I wouldn't use it nor would I recommend anyone else to use it nor would I want to build off of it to support new capabilities, why keep it around?

> A region-specific way of profiling is valuable.

I think one can get the same effect by filtering stack traces and that should be more portable across sampling frameworks.

>  we do not have the support for PERF in place right now

Using `perf` at least doesn't require any application support.

**Comment by insertinterestingnamehere** [comment]
FWIW, `perf` has been more than sufficient for everything I've done and your argument for removing sounds very reasonable to me. That said, others have gone on much deeper dives with profilers than I have, so I'll defer to their preferences.

**Comment by insertinterestingnamehere** [comment]
@l-hoang, do you have any opinion on this?

**Comment by l-hoang** [comment]
I personally mostly use VTune and not PAPI, though that's obviously only if it's available on the machine. I've never actually used much perf, and to be honest I try to avoid using PAPI if at all possible mostly because I hate setting up the counters (though I've used it before and know that it can be useful). :P

I don't have a strong opinion for keeping/removing.

**Comment by roshandathathri** [comment]
> If I wouldn't use it nor would I recommend anyone else to use it nor would I want to build off of it to support new capabilities, why keep it around?

I don't see this as a strong enough reason to remove code. It's code that exists and functions as intended. There is no effort needed as of this release to maintain it. If it becomes derelict, then we can drop it.

**Comment by ddn0** [comment]
> I don't see this as a strong enough reason to remove code. It's code that exists and functions as intended. There is no effort needed as of this release to maintain it.

1. The reason I am bringing up these profilers in the first place is that I trying to clean up our build configuration, so having this code and keeping the documentation up to date is definitely is not free to me. 
2. Having N+1 ways of doing things is potentially confusing internally
3. Having N+1 ways of doing things is confusing externally
4. Code always has a maintenance burden. Its presence must always be weighed against its absence.

**Comment by roshandathathri** [comment]
1 and 4 are fair points. However, they depend on 2 and 3. I do not see perf and VTune as replacements for PAPI (each of them have their own use cases), so 2 and 3 do not hold in this case in my opinion.

**Comment by amberhassaan** [comment]
@ddn0 : Vtune features are a must have, i.e., profiling counters across a specific parallel loop or code region and correlating them with source code (and assembly). Doing this with multiple thread counts shows scalability. My (limited) understanding is that Linux perf does end to end analysis by default, so that's not sufficient for these needs. I believe it is possible to profile sections but I haven't seen a particularly useful library that does this and I don't know how to use the Perf Event API. 

OTOH, PAPI is poor man's tool when we don't have Vtune. It samples counters across a region but doesn't have any stack-sampling type ability to correlate with source code. Perf is better if we can figure out how to do region specific analyses. We haven't zeroed in on a library/method yet, so my suggestion is to let it be until we have a replacement. 

I think perf can replace Vtune & PAPI and that potentially allows people without Vtune to profile their Galois apps.

**Comment by ddn0** [comment]
>  Vtune features are a must have

This issue is about removing PAPI and HPCTK not Vtune.

>> 2. Having N+1 ways of doing things is potentially confusing internally
>> 3. Having N+1 ways of doing things is confusing externally
>
> 2 and 3 do not hold in this case in my opinion

There are people on this thread who do not use the PAPI support because they said it confusing or another tool does it better or another method is more well known.

> OTOH, PAPI is poor man's tool when we don't have Vtune. It samples counters across a region but doesn't have any stack-sampling type ability to correlate with source code. Perf is better if we can figure out how to do region specific analyses. We haven't zeroed in on a library/method yet, so my suggestion is to let it be until we have a replacement.

As I've said, the future is here already, you can simply filter stack traces post-facto or at [sample time](https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/perf-record.txt#L115) yourself. And as a benefit, you don't even have to recompile your code to drill down into different regions. And if you start with end-to-end profiling, you are less likely to optimize the wrong region. And `<`insert all the other reasons why one need not reinvent the wheel wrt performance profiling`>`...

Now, I can see that the points I have been raising haven't been particularly moving to the folks participating in this thread; conversely, I haven't been swayed by any arguments to keep PAPI. Since this is an ISS project at the end of the day, I'll leave the final decision to you.

**Comment by amberhassaan** [comment]
> And if you start with end-to-end profiling, you are less likely to optimize the wrong region.

I recall, as a poor grad student, that sometimes, a minute worth of input parsing didn't matter while 5 seconds of a parallel section were important to scale. I agree that it's wrong in the "real world" but we all have to graduate.

I am convinced that perf is a better replacement of PAPI, but I haven't really tried it except briefly to capture some numbers with Sree. If one of you guys can try out what @ddn0  is suggesting with a lonestar benchmark, perhaps that will convince you guys more.

**Comment by ddn0** [comment]
Looks like the current ISS folks want to keep PAPI in.
