### ISSUE TITLE
Error setting CUDA personality with multiple GPUs

### ISSUE THREAD

**Issue by vancemiller** [IntelligentSoftwareSystems/Galois#19]
In the file dist_apps/src/DistBenchStart.cpp, the line

`164: if (personality_set.length() == (net.Num / num_nodes)) { `

fails to correctly set the personality to GPU_CUDA if an application is launched with a configuration such as `-num_nodes=1 -pset="gg"`, ie. one host with two GPUs.

**Comment by roshandathathri** [comment]
We support only 1 GPU per process, so if the length of the "pset" string is more than the number of processes per node/machine, then it is ignored. 

I'm assuming you are using 1 process for the 2 GPUs. To fix your issue, please use 2 processes (with MPI/LCI).
