### ISSUE TITLE
unit-barriers timeout

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#198]
Observed the following CI failure:

```
380/720 Test   #3: unit-barriers ...........................................................***Timeout 1500.03 sec
```

https://app.circleci.com/pipelines/github/IntelligentSoftwareSystems/Galois/377/workflows/57c3b0ea-faba-4daa-8d13-8eea916d57e3/jobs/7558/steps

I don't think this is easily reproducible since this unit test generally passes.

**Comment by insertinterestingnamehere** [comment]
Yah, this unit test already takes far longer than the others. On one of our 40 core machines it takes several minutes to run while the other tests take around a second each. It's not surprising that it occasionally times out on the CI machines.

**Comment by insertinterestingnamehere** [comment]
Okay, Actually just went back and ran it again. It takes 10 minutes even on one of our 40 core machines. I'm surprised we haven't had issues with the CI builds shutting down after 10 minutes of no output.

**Comment by ddn0** [comment]
I see. `barriers.cpp` takes some command line arguments about number of threads and iterations. Maybe we should just set them to some more reasonable default in the `add_test` command line options.
