### ISSUE TITLE
Prefix all galois-specific CMake options with GALOIS

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#204]
Question: should we bother supporting `USE_EXP` or `USE_STRICT_CONFIG` or `USE_EMBEDDED_REVISION` at all?

Also: remember to update all the scripts, ci, etc.

**Comment by roshandathathri** [comment]
USE_EXP may be okay - not sure if we are using it (after Ian's changes to experimental).

I haven't used the other two. Better to drop them unless there is a specific need.
