### ISSUE TITLE
Error when running applications in lonestar/mining

### ISSUE THREAD

**Issue by bigwater** [IntelligentSoftwareSystems/Galois#208]
Hi,

I am interested in trying out the new Pangolin project. Very nice work! 

When I run the GPU version, it gave me a runtime error. The CPU version works well. 

For example, I am running it in this way: 
```
lonestar/mining/tc_mine/tc_mine_gpu ../lonestar/mining/test_data/citeseer.csgr
```

The error it raised:
```
Galois/libpangolin/gpu/pangolin/graph_gpu.h:353: invalid argument (1)
```

The function that raised the error was
```
void copy_to_gpu(struct CSRGraph& copygraph) {
    copygraph.nnodes = nnodes;
    copygraph.nedges = nedges;
    assert(copygraph.allocOnDevice(use_node_data));
    check_cuda(cudaMemcpy(copygraph.edge_dst, edge_dst,
353:                       nedges * sizeof(index_type), cudaMemcpyHostToDevice));
    check_cuda(cudaMemcpy(copygraph.row_start, row_start,
                          (nnodes + 1) * sizeof(index_type),
                          cudaMemcpyHostToDevice));
    if (use_node_data)
      check_cuda(cudaMemcpy(copygraph.node_data, node_data,
                            nnodes * sizeof(node_data_type),
                            cudaMemcpyHostToDevice));
  }
```

I am using commit 4c77941f (May 7, 2020). 

My configurations:
cmake 3.16.0
CUDA 10.2 + driver 440.33.01
gcc 7.5

I build it with -DENABLE_HETERO_GALOIS=ON. 

I am not sure if I missed something... Any suggestions?

Thank you.

**Comment by roshandathathri** [comment]
Thank you for raising the issue. Xuhao will respond to you. 

Please note that the code is changing rapidly as we are preparing it for a release.

**Comment by insertinterestingnamehere** [comment]
This should be resolved in master now. Thanks!
