### ISSUE TITLE
deprecated copy errors in Boost

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#212]
boost 1.71.0

```
/home/runner/work/katana/katana/libgalois/include/galois/runtime/Executor_DoAll.h:175:17: error: implicitly-declared ‘constexpr boost::iterators::counting_iterator<unsigned int>& boost::iterators::counting_iterator<unsigned int>::operator=(const boost::iterators::counting_iterator<unsigned int>&)’ is deprecated [-Werror=deprecated-copy]
```

https://github.com/KatanaGraph/katana/runs/664855043

**Comment by insertinterestingnamehere** [comment]
This is because of https://github.com/IntelligentSoftwareSystems/Galois/pull/181. I hadn't been able to reproduce the warnings about boost counting iterator. I'll see if there's an easy fix.

**Comment by insertinterestingnamehere** [comment]
Note for reproducing: for whatever reason, this doesn't show up with clang 10, even if the exact same version of boost is used.

**Comment by insertinterestingnamehere** [comment]
@ddn0, oddly enough, I can't reproduce this. I've tried gcc 9 in debug mode on Ubuntu 18.04 with boost 1.71 and no error occurs. I've also tried various other similar build configurations. Any ideas on what might be going on?

**Comment by ddn0** [comment]
It's probably related to the package manager I'm using, `conan`. The 1.71 package had some patches against upstream but I get the same error with the 1.72 package as well. Manual diffing the package and the upstream tarball doesn't reveal many significant differences.

If you want to repro, it would be something like:
```bash
pip install conan
git clone ...katanagraph/katana...
conan install katana/config --build=missing
```

Though I don't know how interesting/important it will be to resolve this.

**Comment by insertinterestingnamehere** [comment]
Weird. Everything at https://github.com/conan-io/conan-center-index/tree/master/recipes/boost/all/patches seems unrelated. When doing my build I'm pulling in unpatched versions in through conda (https://github.com/conda-forge/boost-cpp-feedstock/tree/master/recipe).

**Comment by insertinterestingnamehere** [comment]
@ddn0 are you still having this problem?

**Comment by ddn0** [comment]
Yeah but we just add `-Wno-deprecated-copy` to the build :D
