### ISSUE TITLE
.csgr graph on the input directory.

### ISSUE THREAD

**Issue by nicelhc13** [IntelligentSoftwareSystems/Galois#213]
@insertinterestingnamehere  Could you add the rmat15.csgr?
Some apps using MiningPartitioner.h such as triangle count require cleaned symmetric graphs.
Using .sgr graph is caught by libcusp/include/galois/graphs/MiningPartitioner.h:388 assert().
The current inputs generated by 'make input' do not contain .csgr format.
Thank you

**Comment by insertinterestingnamehere** [comment]
I can add them to the tarball download. Are these files already available somewhere in our inputs directory (`/net/ohm/export/iss/inputs`)?

**Comment by nicelhc13** [comment]
Hi, it is in this path: `/net/ohm/export/iss/dist-inputs/symmetric/`
Thank you very much.

**Comment by insertinterestingnamehere** [comment]
Okay, I'm copying the csgr files for rmat10 and rmat15 to be in `/net/ohm/export/iss/inputs/scalefree/symmetric/rmat15.csgr`. You can refer to it in the tests as `"${BASEINPUT}/scalefree/symmetric/rmat15.csgr"`.

**Comment by insertinterestingnamehere** [comment]
Related: does anyone know why we have different dist-inputs vs inputs directories? The existing testing infrastructure in our CMake configs doesn't really provide a system for referring to multiple input directories.

**Comment by nicelhc13** [comment]
I think @roshandathathri , @gurbinder533  or @l-hoang  can answer your question.

**Comment by roshandathathri** [comment]
We should not be using dist-inputs in our CMake testing scripts. We maintain dist-inputs locally (using soft links) so that we can synchronize across the various clusters we use.
