### ISSUE TITLE
Matrix completion sgd block jump memory leaks

### ISSUE THREAD

**Issue by l-hoang** [IntelligentSoftwareSystems/Galois#218]
/net/fusion/workspace/loc/release/clang/lonestar/analytics/cpu/matrixcompletion/matrixCompletion -algo=sgdBlockJump -lambda=0.001 -learningRate=0.01 -learningRateFunction=intel -tolerance=0.01 -useSam
eLatentVector -useDetInit /net/ohm/export/iss/inputs/weighted/bipartite/Epinions_dataset.gr -t 1

=================================================================
==33174==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 856152 byte(s) in 1 object(s) allocated from:
    #0 0x50ed77 in operator new[](unsigned long) /workspace/tmp_llvm_build/llvm/compiler-rt/lib/asan/asan_new_delete.cpp:102:3
    #1 0x5dcbcd in SGDBlockJumpAlgo::operator()(galois::graphs::LC_CSR_Graph<SGDBlockJumpAlgo::Node, float, true, false, false, float>&, StepFunction const&) /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:579:25
    #2 0x518b30 in void run<SGDBlockJumpAlgo>() /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1465:3
    #3 0x511e2f in main /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1512:5
    #4 0x7ff1dc338554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    
Direct leak of 18048 byte(s) in 1 object(s) allocated from:
    #0 0x50f237 in operator new[](unsigned long, std::align_val_t) /workspace/tmp_llvm_build/llvm/compiler-rt/lib/asan/asan_new_delete.cpp:114:3
    #1 0x5dc8c5 in SGDBlockJumpAlgo::operator()(galois::graphs::LC_CSR_Graph<SGDBlockJumpAlgo::Node, float, true, false, false, float>&, StepFunction const&) /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:571:24
    #2 0x518b30 in void run<SGDBlockJumpAlgo>() /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1465:3
    #3 0x511e2f in main /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1512:5
    #4 0x7ff1dc338554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    
Direct leak of 8832 byte(s) in 1 object(s) allocated from:
    #0 0x50f237 in operator new[](unsigned long, std::align_val_t) /workspace/tmp_llvm_build/llvm/compiler-rt/lib/asan/asan_new_delete.cpp:114:3
    #1 0x5dc818 in SGDBlockJumpAlgo::operator()(galois::graphs::LC_CSR_Graph<SGDBlockJumpAlgo::Node, float, true, false, false, float>&, StepFunction const&) /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:570:24
    #2 0x518b30 in void run<SGDBlockJumpAlgo>() /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1465:3
    #3 0x511e2f in main /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1512:5
    #4 0x7ff1dc338554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    
Indirect leak of 13604040 byte(s) in 9729 object(s) allocated from:
    #0 0x50ed77 in operator new[](unsigned long) /workspace/tmp_llvm_build/llvm/compiler-rt/lib/asan/asan_new_delete.cpp:102:3
    #1 0x5dd009 in SGDBlockJumpAlgo::operator()(galois::graphs::LC_CSR_Graph<SGDBlockJumpAlgo::Node, float, true, false, false, float>&, StepFunction const&) /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:593:26
    #2 0x518b30 in void run<SGDBlockJumpAlgo>() /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1465:3
    #3 0x511e2f in main /net/fusion/workspace/loc/release/Galois/lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp:1512:5
    #4 0x7ff1dc338554 in __libc_start_main (/lib64/libc.so.6+0x22554)

**Comment by l-hoang** [comment]
Ran on the debug build on 40-core machine built with clang with sanitizer on.

**Comment by bozhiyou** [comment]
Fixed by #258. Closing this.
