### ISSUE TITLE
Unused parameter 'syncType'

### ISSUE THREAD

**Issue by vishweshjatala** [IntelligentSoftwareSystems/Galois#228]
Fedora-clang build fails with the following error:

In file included from /root/project/lonestar/libdistbench/include/DistMiningBenchStart.h:31:
/root/project/libgluon/include/galois/graphs/GluonEdgeSubstrate.h:103:30: error: unused parameter 'syncType' [-Werror,-Wunused-parameter]
  void reset_bitset(SyncType syncType,
                             ^
1 error generated.
gmake[2]: *** [lonestar/analytics/distributed/tc/CMakeFiles/tc.dir/build.make:83: lonestar/analytics/distributed/tc/CMakeFiles/tc.dir/tc.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:4917: lonestar/analytics/distributed/tc/CMakeFiles/tc.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
 
You can check the issue below:
https://app.circleci.com/pipelines/github/vishweshjatala/Galois/5/workflows/17d8273e-30b9-49d1-ba7b-3a228dfcbcb2/jobs/100/steps

**Comment by l-hoang** [comment]
Remove the variable name ("syncType") from the signature and it should build.

**Comment by vishweshjatala** [comment]
Fedora-clang build passes now. Closing it.
