### ISSUE TITLE
Create generic HW Topo backend

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#243]
Create generic topology information if we run on unknown operating systems.

context: https://github.com/IntelligentSoftwareSystems/Galois/pull/201

**Comment by ddn0** [comment]
@insertinterestingnamehere I think the biggest hurdle is that at a minimum we would like to know the maximum number of threads on a system, I don't know how we can do this generically. The alternative would be to pick some static number that is "good enough"(tm). Supporting dynamic number of threads is also an option but that might require rethinking some of the per-thread interfaces and initialization.

**Comment by insertinterestingnamehere** [comment]
Would `std::thread::hardware_concurrency` be good enough? I'm not sure what that would do on a cloud machine, but it seems like a reasonable initial guess.

**Comment by insertinterestingnamehere** [comment]
https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency

**Comment by ddn0** [comment]
`std::thread::hardware_concurrency` sounds reasonable; though it is totally possible that will just return `0`. Should we just be `abort` in that case or should we pretend to have some number of threads?

**Comment by insertinterestingnamehere** [comment]
Great question. I'm not sure. My best guess is to make it an error. The standard libraries appear to be putting some effort into getting the hardware info, so hopefully failures will be rare. See https://github.com/llvm/llvm-project/blob/4d25f4453d60dee522e905c844dde0f4b6ed9475/libcxx/src/thread.cpp#L81, https://github.com/gcc-mirror/gcc/blob/4bc701d37fb90229e7337bfd8f510bb74fb1aadf/libstdc%2B%2B-v3/src/c%2B%2B11/thread.cc#L34, and https://github.com/microsoft/STL/blob/2c441c7e03dbce45a0048a531af23f7561a25cd4/stl/src/cthread.cpp#L101.

If erroring out is a concern though, maybe we can fall back on some Galois-specific environment variable?

**Comment by ddn0** [comment]
Let's error out for now; the most likely casualty will be hardware simulators and I'm sure they can find their own workarounds.
