### ISSUE TITLE
Convert StatTimer to fully RAII API

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#263]
Instead of
```
StatTimer timer;
timer.start();
// timed region
timer.stop();
```
Remove `start` and `stop` and use RAII:
```
{
  StatTimer timer;
  // timed region
}
```

This does imply some moderate refactoring of existing benchmarks because timing regions need to follow variable scopes but that should lead to better code in general, so, on balance, it seems a reasonable trade-off for an API that is less likely to be misused. RAII ensures regions are nested or disjoint while unstructured `start` and `stop` may accidentally lead to overlapping timed regions.

Initial Context: #262

**Comment by l-hoang** [comment]
👍 

Might break some existing code where timers are being passed across scopes and start/stopped in differing scopes, but that probably just means that code needs a rewrite/refactoring anyways since things aren't in functional units.
