### ISSUE TITLE
Make test

### ISSUE THREAD

**Issue by nicelhc13** [IntelligentSoftwareSystems/Galois#264]
I found that some applications (e.g. mining cpu apps) still do not have the make tests. I believe that more apps would not have the make test. From this release, I learned power of the make test in terms of stability. It would be good timing to put 'make test' on all the applications since we are on the final phase of the release and we are left with the tasks that would be applied globally.

**Comment by nicelhc13** [comment]
I checked which apps do not have 'make test.'
Please check and add tests if you can.

lonestar/analytics/cpu/betweennesscentrality/betweennesscentrality-async
lonestar/analytics/cpu/betweennesscentrality/betweennesscentrality-level
lonestar/analytics/cpu/triangle-counting/trianglesAOS
lonestar/anayltics/distributed/matrixcompletion/matrixcompletion
lonestar/analytics/gpu/*
lonestar/scientific/gpu/*

**Comment by roshandathathri** [comment]
Thanks, Hochan, Yes, all these apps should have make tests, preferably for the release. 

Just to be clear, here is the owner for creating tests for each app:

- @l-hoang : lonestar/analytics/cpu/betweennesscentrality/betweennesscentrality-async
- @l-hoang : lonestar/analytics/cpu/betweennesscentrality/betweennesscentrality-level
- @l-hoang : lonestar/analytics/cpu/triangle-counting/trianglesAOS
- @gurbinder533 : lonestar/anayltics/distributed/matrixcompletion/matrixcompletion
- @vishweshjatala : lonestar/analytics/gpu/*
- @chenxuhao : lonestar/scientific/gpu/*
- @chenxuhao : lonestar/mining/cpu/subgraph-listing

**Comment by chenxuhao** [comment]
subgraph-listing should not be in Pangolin (Sandslash only). I removed it. Added gpu make test for dmr, sgd, mis, mst, pta.

**Comment by vishweshjatala** [comment]
Please close this if @l-hoang and @gurbinder533 also have finished their sections.
