### ISSUE TITLE
CMake target might need a prefix

### ISSUE THREAD

**Issue by nicelhc13** [IntelligentSoftwareSystems/Galois#270]
I am in the middle of the renaming works.
All the renaming is done based on the doc:
[https://docs.google.com/spreadsheets/d/1EgHplvslmZGIkkJz0NdxMbCd60nDzTg_Laoa81j7zgo/edit#gid=0]

On that doc, we decided to use the same binary names, but it generated cmake conflict with the below errors:

> 
> -- NOT compiling loop-overhead (missing: OPENMP_FOUND)
> CMake Error at lonestar/mining/cpu/triangle-counting/CMakeLists.txt:1 (add_executable):
>   add_executable cannot create target "triangle-counting" because another
>   target with the same name already exists.  The existing target is an
>   executable created in source directory
>   "/h1/hlee/far_hlee/workspace/Galois.release/lonestar/analytics/cpu/triangle-counting".
>   See documentation for policy CMP0002 for more details.
> 

Has anyone a solution or suggestions?

**Comment by insertinterestingnamehere** [comment]
To get this working please prefix the mining version with "mining". We can confirm that this is the right fix tomorrow.

**Comment by nicelhc13** [comment]
Thank you. It would also happen between distributed and shared analytic apps. I will also attach "dist" to the distributed apps.

**Comment by insertinterestingnamehere** [comment]
Sounds good. Thanks!
