### ISSUE TITLE
Tests failing for distributed TC app on CPU

### ISSUE THREAD

**Issue by roshandathathri** [IntelligentSoftwareSystems/Galois#276]
Here are all the failing tests:
```
1645:run-tc-sync-cpu-rmat15-oec-1
1646:run-tc-sync-cpu-rmat15-oec-2
1647:run-tc-sync-cpu-rmat15-oec-4
1648:run-tc-sync-cpu-rmat15-oec-8
1651:run-tc-sync-cpugpu-rmat15-oec-1
1652:run-tc-sync-cpu-rmat15-iec-1
1653:run-tc-sync-cpu-rmat15-iec-2
1654:run-tc-sync-cpu-rmat15-iec-4
1655:run-tc-sync-cpu-rmat15-iec-8
1658:run-tc-sync-cpugpu-rmat15-iec-1
1659:run-tc-sync-cpu-rmat15-cvc-1
1660:run-tc-sync-cpu-rmat15-cvc-2
1661:run-tc-sync-cpu-rmat15-cvc-4
1662:run-tc-sync-cpu-rmat15-cvc-8
1665:run-tc-sync-cpugpu-rmat15-cvc-1
1666:run-tc-sync-cpu-rmat15-cvc-iec-1
1667:run-tc-sync-cpu-rmat15-cvc-iec-2
1668:run-tc-sync-cpu-rmat15-cvc-iec-4
1669:run-tc-sync-cpu-rmat15-cvc-iec-8
1672:run-tc-sync-cpugpu-rmat15-cvc-iec-1
1673:run-tc-sync-cpu-rmat15-hovc-1
1674:run-tc-sync-cpu-rmat15-hovc-2
1675:run-tc-sync-cpu-rmat15-hovc-4
1676:run-tc-sync-cpu-rmat15-hovc-8
1679:run-tc-sync-cpugpu-rmat15-hovc-1
1680:run-tc-sync-cpu-rmat15-hivc-1
1681:run-tc-sync-cpu-rmat15-hivc-2
1682:run-tc-sync-cpu-rmat15-hivc-4
1683:run-tc-sync-cpu-rmat15-hivc-8
1686:run-tc-sync-cpugpu-rmat15-hivc-1
```

**Comment by nicelhc13** [comment]
I reproduced the error, but the dist-tc-cpu "itself" does not have a problem. If I disable the gpu through the cmake, then dist-tc passed all the tests. Otherwise, it failed during the gpu graph masharling phase. @vishweshjatala  Could you help this issue?

**Comment by roshandathathri** [comment]
Thanks @nicelhc13 

@vishweshjatala It seems like #ifdef for GPU is missing. It should be a simple fix.

**Comment by vishweshjatala** [comment]
I will look into it now.

**Comment by vishweshjatala** [comment]
I fixed the personality issue. All the test case pass now. Created a pull request (https://github.com/IntelligentSoftwareSystems/Galois/pull/278). Closing it now. Please reopen if you have any issue with it.
Test project /h2/vjatala/Desktop/Galois_Forked_Github/Galois/build/master/lonestar/analytics/distributed/tc
      Start  1: run-tc-sync-cpu-rmat15-oec-1
 1/42 Test  #1: run-tc-sync-cpu-rmat15-oec-1 ..........   Passed    0.89 sec
      Start  2: run-tc-sync-cpu-rmat15-oec-2
 2/42 Test  #2: run-tc-sync-cpu-rmat15-oec-2 ..........   Passed    0.91 sec
      Start  3: run-tc-sync-cpu-rmat15-oec-4
 3/42 Test  #3: run-tc-sync-cpu-rmat15-oec-4 ..........   Passed    1.36 sec
      Start  4: run-tc-sync-cpu-rmat15-oec-8
 4/42 Test  #4: run-tc-sync-cpu-rmat15-oec-8 ..........   Passed    2.71 sec
      Start  5: run-tc-sync-gpu-rmat15-oec-1
 5/42 Test  #5: run-tc-sync-gpu-rmat15-oec-1 ..........   Passed    0.73 sec
      Start  6: run-tc-sync-gpu-rmat15-oec-2
 6/42 Test  #6: run-tc-sync-gpu-rmat15-oec-2 ..........   Passed    1.17 sec
      Start  7: run-tc-sync-cpugpu-rmat15-oec-1
 7/42 Test  #7: run-tc-sync-cpugpu-rmat15-oec-1 .......   Passed    0.64 sec
      Start  8: run-tc-sync-cpu-rmat15-iec-1
 8/42 Test  #8: run-tc-sync-cpu-rmat15-iec-1 ..........   Passed    0.72 sec
      Start  9: run-tc-sync-cpu-rmat15-iec-2
 9/42 Test  #9: run-tc-sync-cpu-rmat15-iec-2 ..........   Passed    1.04 sec
      Start 10: run-tc-sync-cpu-rmat15-iec-4
10/42 Test #10: run-tc-sync-cpu-rmat15-iec-4 ..........   Passed    1.44 sec
      Start 11: run-tc-sync-cpu-rmat15-iec-8
11/42 Test #11: run-tc-sync-cpu-rmat15-iec-8 ..........   Passed    2.70 sec
      Start 12: run-tc-sync-gpu-rmat15-iec-1
12/42 Test #12: run-tc-sync-gpu-rmat15-iec-1 ..........   Passed    0.74 sec
      Start 13: run-tc-sync-gpu-rmat15-iec-2
13/42 Test #13: run-tc-sync-gpu-rmat15-iec-2 ..........   Passed    1.20 sec
      Start 14: run-tc-sync-cpugpu-rmat15-iec-1
14/42 Test #14: run-tc-sync-cpugpu-rmat15-iec-1 .......   Passed    0.70 sec
      Start 15: run-tc-sync-cpu-rmat15-cvc-1
15/42 Test #15: run-tc-sync-cpu-rmat15-cvc-1 ..........   Passed    0.67 sec
      Start 16: run-tc-sync-cpu-rmat15-cvc-2
16/42 Test #16: run-tc-sync-cpu-rmat15-cvc-2 ..........   Passed    0.95 sec
      Start 17: run-tc-sync-cpu-rmat15-cvc-4
17/42 Test #17: run-tc-sync-cpu-rmat15-cvc-4 ..........   Passed    1.50 sec
      Start 18: run-tc-sync-cpu-rmat15-cvc-8
18/42 Test #18: run-tc-sync-cpu-rmat15-cvc-8 ..........   Passed    2.70 sec
      Start 19: run-tc-sync-gpu-rmat15-cvc-1
19/42 Test #19: run-tc-sync-gpu-rmat15-cvc-1 ..........   Passed    0.72 sec
      Start 20: run-tc-sync-gpu-rmat15-cvc-2
20/42 Test #20: run-tc-sync-gpu-rmat15-cvc-2 ..........   Passed    1.16 sec
      Start 21: run-tc-sync-cpugpu-rmat15-cvc-1
21/42 Test #21: run-tc-sync-cpugpu-rmat15-cvc-1 .......   Passed    0.72 sec
      Start 22: run-tc-sync-cpu-rmat15-cvc-iec-1
22/42 Test #22: run-tc-sync-cpu-rmat15-cvc-iec-1 ......   Passed    0.73 sec
      Start 23: run-tc-sync-cpu-rmat15-cvc-iec-2
23/42 Test #23: run-tc-sync-cpu-rmat15-cvc-iec-2 ......   Passed    0.97 sec
      Start 24: run-tc-sync-cpu-rmat15-cvc-iec-4
24/42 Test #24: run-tc-sync-cpu-rmat15-cvc-iec-4 ......   Passed    1.51 sec
      Start 25: run-tc-sync-cpu-rmat15-cvc-iec-8
25/42 Test #25: run-tc-sync-cpu-rmat15-cvc-iec-8 ......   Passed    2.73 sec
      Start 26: run-tc-sync-gpu-rmat15-cvc-iec-1
26/42 Test #26: run-tc-sync-gpu-rmat15-cvc-iec-1 ......   Passed    0.69 sec
      Start 27: run-tc-sync-gpu-rmat15-cvc-iec-2
27/42 Test #27: run-tc-sync-gpu-rmat15-cvc-iec-2 ......   Passed    1.27 sec
      Start 28: run-tc-sync-cpugpu-rmat15-cvc-iec-1
28/42 Test #28: run-tc-sync-cpugpu-rmat15-cvc-iec-1 ...   Passed    0.74 sec
      Start 29: run-tc-sync-cpu-rmat15-hovc-1
29/42 Test #29: run-tc-sync-cpu-rmat15-hovc-1 .........   Passed    0.74 sec
      Start 30: run-tc-sync-cpu-rmat15-hovc-2
30/42 Test #30: run-tc-sync-cpu-rmat15-hovc-2 .........   Passed    1.03 sec
      Start 31: run-tc-sync-cpu-rmat15-hovc-4
31/42 Test #31: run-tc-sync-cpu-rmat15-hovc-4 .........   Passed    1.52 sec
      Start 32: run-tc-sync-cpu-rmat15-hovc-8
32/42 Test #32: run-tc-sync-cpu-rmat15-hovc-8 .........   Passed    2.68 sec
      Start 33: run-tc-sync-gpu-rmat15-hovc-1
33/42 Test #33: run-tc-sync-gpu-rmat15-hovc-1 .........   Passed    0.70 sec
      Start 34: run-tc-sync-gpu-rmat15-hovc-2
34/42 Test #34: run-tc-sync-gpu-rmat15-hovc-2 .........   Passed    1.25 sec
      Start 35: run-tc-sync-cpugpu-rmat15-hovc-1
35/42 Test #35: run-tc-sync-cpugpu-rmat15-hovc-1 ......   Passed    0.71 sec
      Start 36: run-tc-sync-cpu-rmat15-hivc-1
36/42 Test #36: run-tc-sync-cpu-rmat15-hivc-1 .........   Passed    0.72 sec
      Start 37: run-tc-sync-cpu-rmat15-hivc-2
37/42 Test #37: run-tc-sync-cpu-rmat15-hivc-2 .........   Passed    1.03 sec
      Start 38: run-tc-sync-cpu-rmat15-hivc-4
38/42 Test #38: run-tc-sync-cpu-rmat15-hivc-4 .........   Passed    1.46 sec
      Start 39: run-tc-sync-cpu-rmat15-hivc-8
39/42 Test #39: run-tc-sync-cpu-rmat15-hivc-8 .........   Passed    2.66 sec
      Start 40: run-tc-sync-gpu-rmat15-hivc-1
40/42 Test #40: run-tc-sync-gpu-rmat15-hivc-1 .........   Passed    0.69 sec
      Start 41: run-tc-sync-gpu-rmat15-hivc-2
41/42 Test #41: run-tc-sync-gpu-rmat15-hivc-2 .........   Passed    1.23 sec
      Start 42: run-tc-sync-cpugpu-rmat15-hivc-1
42/42 Test #42: run-tc-sync-cpugpu-rmat15-hivc-1 ......   Passed    0.67 sec

100% tests passed, 0 tests failed out of 42

Label Time Summary:
quick    =  51.12 sec*proc (42 tests)
