### ISSUE TITLE
Integrate support for CUDA compute capability >7.0 into Katana

### ISSUE THREAD

**Issue by yuhc** [IntelligentSoftwareSystems/Galois#287]
The GPU applications' code in Katana repo are out of date and don't support Turing GPUs.

The related issue in Katana repo is https://github.com/KatanaGraph/katana/issues/72.

**Comment by vishweshjatala** [comment]
@chenxuhao  Please upgrade PTA app. There are multiple instance of such errors. Please replace __shfl, __any, __all, __ballot instructions with __shfl_sync, __any_sync, __all_sync, __ballot_sync instructions. You can refer to the following page https://devblogs.nvidia.com/using-cuda-warp-level-primitives/
ptxas /tmp/tmpxft_0000e225_00000000-6_pta.compute_70.ptx, line 12550; error   : Instruction 'vote' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_0000e225_00000000-6_pta.compute_70.ptx, line 12666; error   : Instruction 'vote' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4

**Comment by vishweshjatala** [comment]
ModernGPU is also updated. Created a pull request https://github.com/IntelligentSoftwareSystems/Galois/pull/305. 
@chenxuhao  also a created PR https://github.com/IntelligentSoftwareSystems/Galois/pull/302 to fix other GPU app.
Now this can be closed after merging.

**Comment by roshandathathri** [comment]
Closed via #302 and #305
