### ISSUE TITLE
connected-components-pull-dist returns incorrect result

### ISSUE THREAD

**Issue by timjbaer** [IntelligentSoftwareSystems/Galois#304]
`mpirun -n=1 ./connected-components-pull-dist conv_sample.gr -symmetricGraph -t=1` incorrectly returns `Number of components is 3` (should be 1) for the following sample graph from DIMACS (which was converted to Galois binary):  
```
c 9th DIMACS Implementation Challenge: Shortest Paths
c http://www.dis.uniroma1.it/~challenge9
c Sample graph file
c
p sp 6 8
c graph contains 6 nodes and 8 arcs
c node ids are numbers in 1..6
c
a 1 2 17
c arc from node 1 to node 2 of weight 17
c
a 1 3 10
a 2 4 2
a 3 5 0
a 4 3 0
a 4 6 3
a 5 2 0
a 5 6 20
```

Interestingly, `connected-components-push-dist` returns the correct result (1).

**Comment by roshandathathri** [comment]
DIMACS inputs typically need many iterations and the default maximum number of iterations is 1000. Please increase that and check if you're still getting incorrect results. 

Please check the stats file to see the number of iterations/rounds executed. If it is the same as the maximum number of iterations chosen, then the algorithm might not have converged (if so, the results will be incorrect).

**Comment by l-hoang** [comment]
Hello. Thank you for using Galois.

After you converted from dimac to the Galois binary, did you make the graph symmetric as well? Connected components requires a symmetric input (i.e., if edge a->b exists, then b->a should exist as well). The graph convert tool has a gr2sgr option you can use.

**Comment by timjbaer** [comment]
The DIMAC file was really small and only required 5 iterations.

Converting the graph to symmetric fixed the issue. I had assumed the `-symmetricGraph` flag would take care of this.

Thanks the quick responses!
