### ISSUE TITLE
libpangolin Needs a README

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#310]
libpangolin needs a README. The README file should also specifically mention that Pangolin uses BLISS which is not licensed under the same license as the rest of Galois.

**Comment by chenxuhao** [comment]
There was a README. Someone removed it.

**Comment by chenxuhao** [comment]
Please help me find it back. I will update it then.

**Comment by insertinterestingnamehere** [comment]
Found it. Thanks for the heads up. I've revived it in https://github.com/IntelligentSoftwareSystems/Galois/pull/314.

**Comment by roshandathathri** [comment]
Closed via #302
