### ISSUE TITLE
graph-convert: Invalid argument: failed writing to...

### ISSUE THREAD

**Issue by pwrliang** [IntelligentSoftwareSystems/Galois#315]
Hi, there

I'm trying to convert a matrix market graph to .gr format. I can convert successfully with a smaller dataset. But I failed to convert with soc-twitter dataset.

```
L-L3XUG8WN-1736:build liang$ ./tools/graph-convert/graph-convert --mtx2gr --edgeType=int32 /Users/liang/Downloads/soc-twitter-2010/soc-twitter-2010.mtx /Users/liang/Downloads/soc-twitter-2010/soc-twitter-2010.gr
Graph type: int32
Phase 0: current edge progress 0.000000%
Phase 0: current edge progress 0.200000%
Phase 0: current edge progress 0.400000%
Phase 0: current edge progress 0.599999%
..........
..........
Phase 1: current edge progress 99.399884%
Phase 1: current edge progress 99.599884%
Phase 1: current edge progress 99.799884%
Phase 1: current edge progress 99.999883%
ERROR: /Users/liang/Projects/Galois/libgalois/src/FileGraph.cpp:525: Invalid argument: failed writing to '/Users/liang/Downloads/soc-twitter-2010/soc-twitter-2010.gr'
Abort trap: 6
```

Environment:
```
URL: http://nrvis.com/download/data/massive/soc-twitter-2010.zip
Command: ./graph-convert --mtx2gr --edgeType=int32 /Users/liang/Downloads/soc-twitter-2010/soc-twitter-2010.mtx /Users/liang/Downloads/soc-twitter-2010/soc-twitter-2010.gr
OS: Mac OS 10.14.5
Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
```

I have checked the space is enough, and the location is also valid. How can I fix this?

Thanks,
Liang

**Comment by l-hoang** [comment]
Hello.

May you provide a link to the mtx dataset?

The error that you are getting arises when the write syscall fails to write to the specified location. Does the directory have write permissions on it? (I'm assuming that's what you mean by the location being valid.)

Thank you.

**Comment by pwrliang** [comment]
@l-hoang Hi, the link is here: [dataset](http://nrvis.com/download/data/massive/soc-twitter-2010.zip). I'm sure the output location is valid and have write permissions on it.

Thanks.

**Comment by l-hoang** [comment]
Hello.

I just tried conversion with this command:

./graph-convert --mtx2gr --edgeType=int32  soc-twitter-2010.mtx asdf.gr

I was able to successfully convert it to a 2.2G file here:
-rw-r--r-- 1 lhoang cdgc 2.2G Jun 12 23:44 asdf.gr

I am not sure what is occurring on your end. Have you tried with a smaller dataset?

Thank you,
Loc

**Comment by pwrliang** [comment]
Hi Loc,

Yes, I can convert [smaller dataset](https://www.cise.ufl.edu/research/sparse/MM/Rommes/bips98_606.tar.gz) as I mentioned before. I have tried your command: `./graph-convert --mtx2gr --edgeType=int32 soc-twitter-2010.mtx asdf.gr` but still the same: `FileGraph.cpp:525: Invalid argument: failed writing to 'asdf.gr'`.
Don't worry, I can still use the old version. I was used to convert the dataset on a Linux machine with Galois 2.2, and that works like a charm.

Regards,
Liang

**Comment by l-hoang** [comment]
Interesting, so 2.2 works. I'll keep this open as an issue as that probably means something changed since the very old 2.2 release. There might be some assumption about how things are being written.

Thanks for catching this for us!

Regards,
Loc

**Comment by roshandathathri** [comment]
@pwrliang can you please share the hardware configuration of your machine and the filesystem that you are writing to?

**Comment by pwrliang** [comment]
> @pwrliang can you please share the hardware configuration of your machine and the filesystem that you are writing to?

Filesystem:
```
   Device Identifier:         disk0s2
   Device Node:               /dev/disk0s2
   Whole:                     No
   Part of Whole:             disk0

   Volume Name:               mac
   Mounted:                   Yes
   Mount Point:               /

   Partition Type:            Apple_HFS
   File System Personality:   Journaled HFS+
   Type (Bundle):             hfs
   Name (User Visible):       Mac OS Extended (Journaled)
   Journal:                   Journal size 24576 KB at offset 0x74e000
   Owners:                    Enabled

   OS Can Be Installed:       Yes
   Media Type:                Generic
   Protocol:                  PCI
   SMART Status:              Verified
   Volume UUID:               -------
   Disk / Partition UUID:     -------
   Partition Offset:          209735680 Bytes (409640 512-Byte-Device-Blocks)

   Disk Size:                 250.7 GB (250656219136 Bytes) (exactly 489562928 512-Byte-Units)
   Device Block Size:         512 Bytes

   Volume Total Space:        250.7 GB (250656219136 Bytes) (exactly 489562928 512-Byte-Units)
   Volume Used Space:         115.0 GB (114955055104 Bytes) (exactly 224521592 512-Byte-Units) (45.9%)
   Volume Free Space:         135.7 GB (135701164032 Bytes) (exactly 265041336 512-Byte-Units) (54.1%)
   Allocation Block Size:     4096 Bytes

   Read-Only Media:           No
   Read-Only Volume:          No

   Device Location:           Internal
   Removable Media:           Fixed

   Solid State:               Yes
   Hardware AES Support:      No
```

Hardware configuration:
```
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	MBP114.0184.B00
  SMC Version (system):	2.29f24
```
