### ISSUE TITLE
Is it possible to build the lonestar scientific applications using clang and openmp?

### ISSUE THREAD

**Issue by abhaypotharaju** [IntelligentSoftwareSystems/Galois#318]
I have tried editing the cmake files in the Build folder to change the compiler to clang and added the additional flags required to compile the program correctly. I have also changed the CXX path in the CMakeCXXCompler.cmake file. However, upon making the lonestar applications they are compiled using c++ and all the changes made to the files are lost (I'm assuming I'm not editing the right files here). I wish to build the lonestar scientific applications using clang and openmp.

**Comment by insertinterestingnamehere** [comment]
Galois doesn't use OpenMP anywhere except the unit tests. Do you mean OpenMPI? Provided that you have clang 7 or newer, you should be able to build with clang by configuring with something like

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ <source_directory>`
