### ISSUE TITLE
Boost version related issue while trying to use cmake

### ISSUE THREAD

**Issue by ArindamK92** [IntelligentSoftwareSystems/Galois#358]
I am trying to compile Galois and getting the below Boost error. It is complaining about Boost version that the version should be more than  "1.58.0", but I am using "1.65.1". So, it should not be a version problem I guess. Please help about it.

akhanda@arya:~/Galois/Galois$ cmake -S $SRC_DIR -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release
-- Try architecture flag = [-march=native]
CMake Error at /snap/cmake/372/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: iostreams) (found suitable version "1.65.1",
  minimum required is "1.58.0")
Call Stack (most recent call first):
  /snap/cmake/372/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /snap/cmake/372/share/cmake-3.17/Modules/FindBoost.cmake:2166 (find_package_handle_standard_args)
  CMakeLists.txt:155 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/users/akhanda/Galois/Galois/buildDir/CMakeFiles/CMakeOutput.log".
See also "/home/users/akhanda/Galois/Galois/buildDir/CMakeFiles/CMakeError.log".
akhanda@arya:~/Galois/Galois$ cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_65_1"

**Comment by roshandathathri** [comment]
From the log, it looks like the boost_iostreams library is missing. Please run "locate libboost_iostreams.so" and check if it is present on your machine. If it is, please make its path available to cmake.

**Comment by roshandathathri** [comment]
I'm closing this issue. Please reopen if you are still facing this issue.
