### ISSUE TITLE
fail to download LCI

### ISSUE THREAD

**Issue by photoszzt** [IntelligentSoftwareSystems/Galois#367]
I try to enable LCI but it requires password to download the repo.

**Comment by roshandathathri** [comment]
Hi Zhiting,

Yes, that's expected. LCI is developed by Marc Snir's group at UIUC. If you want to use it, please email Marc.

You can use Galois without LCI and it performs/scales well. You can use any MPI implementation with it but there are different flags that may be required for different implementations to disable binding and to enable multi-threaded communication. Please let us know if you have any issues.

Thanks,
Roshan
