### ISSUE TITLE
mpi not executed in bfs_pull aplication(distributed vertion)

### ISSUE THREAD

**Issue by shuiipkw** [IntelligentSoftwareSystems/Galois#37]
when I use the command:  mpirun -n 4 -host=IIPLab-WS2,IIPLab-WS1 ./bfs_pull /home/mpi_ share/KW/bgg.gr -numnodes=2 
the runtime error is:
===========================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 4774 RUNNING AT IIPLab-WS1
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===========================================================================
[proxy:0:1@IIPLab-WS2] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:878): assert (!closed) failed
[proxy:0:1@IIPLab-WS2] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:1@IIPLab-WS2] main (pm/pmiserv/pmip.c:200): demux engine error waiting for event
[mpiexec@IIPLab-WS2] HYDT_bscu_wait_for_completion (tools/bootstrap/utils/bscu_wait.c:75): one of the processes terminated badly; aborting
[mpiexec@IIPLab-WS2] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:22): launcher returned error waiting for completion
[mpiexec@IIPLab-WS2] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:215): launcher returned error waiting for completion
[mpiexec@IIPLab-WS2] main (ui/mpich/mpiexec.c:336): process manager error waiting for completion

**Comment by roshandathathri** [comment]
I'm assuming this issue is the same as the one in:
https://github.com/IntelligentSoftwareSystems/Galois/issues/36

If it isn't, please reopen the issue.
