### ISSUE TITLE
Connected Components Symmetric Graph?

### ISSUE THREAD

**Issue by chris1274** [IntelligentSoftwareSystems/Galois#370]
Looking at the connectedcomponents usage message, I see it is asking for a symmetric graph. Does this mean undirected, as in symmetric relation on the vertices, or something like this https://en.wikipedia.org/wiki/Symmetric_graph? I guess it would only make sense if it meant undirected, but I am still confused by this. Please let me know, thanks.

**Comment by roshandathathri** [comment]
Our input graph format represents a directed graph. For an undirected graph, the input must be a symmetric, directed graph. So we mean symmetric graph as defined in the wiki page.

**Comment by chris1274** [comment]
Ok, thanks - I understand by symmetric you mean undirected, but for the record that is not the same as what the wikipedia page is describing...

**Comment by roshandathathri** [comment]
Sorry for the confusion. Yes, we do not mean symmetric as it is defined in that link you posted. We mean "symmetric digraph" or "symmetric directed graph" as defined here:
https://en.wikipedia.org/wiki/Directed_graph#Types_of_directed_graphs

**Comment by chris1274** [comment]
Ah, I see. Thank you for the quick response!
