### ISSUE TITLE
Input Graphs in Galois Paper

### ISSUE THREAD

**Issue by chris1274** [IntelligentSoftwareSystems/Galois#371]
I have a question regarding this publication on the Galois system: https://arxiv.org/pdf/1904.07162.pdf. In figure 9, I see numbers for pagerank and connected components for the same graph. My understanding is that pagerank is applicable to directed graphs and connected components to undirected graphs, so how are both of them being run on the same graph? Are you doing something like adding in the reverse edges before running CC?

**Comment by roshandathathri** [comment]
Yes, CC is weakly connected components, so we consider each edge to be undirected (this is the same for k-core as well). You can use our graph-convert in tools to symmetrize and clean the original graph.
