### ISSUE TITLE
Is Gluon-Async integrated into the repo?

### ISSUE THREAD

**Issue by Steamgjk** [IntelligentSoftwareSystems/Galois#390]
I read the paper "Gluon-Async: A Bulk-Asynchronous System for Distributed and Heterogeneous Graph Analytics" and grow much interest in it. So I am wondering whether gluo-async is usable in the current repo. 

I made a fast skim of the lib-gluon, it seems there are only sync-related stuff but not async-related stuff.

**Comment by roshandathathri** [comment]
Thanks for your interest in our work. 

Gluon-Async is available in both 6.0 and master branches as a template parameter to the `GluonSubstrate::sync()` function:
https://github.com/IntelligentSoftwareSystems/Galois/blob/release-6.0/libgluon/include/galois/graphs/GluonSubstrate.h#L3045
https://github.com/IntelligentSoftwareSystems/Galois/blob/release-6.0/lonestar/analytics/distributed/bfs/bfs_push.cpp#L252
