### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by Steamgjk** [IntelligentSoftwareSystems/Galois#393]
<img width="583" alt="图片" src="https://user-images.githubusercontent.com/7100589/155853129-0de6bd1b-2afd-4102-9535-fa6bb538917e.png">

I can successfully compile and run the tutorial examples.
However, when I try to compile the entire project with make -j, I encountered the failure.
It also makes the VM dead (Seems it hajacks my terminal and I cannot even open new terminals to kill it), and I have to reboot the VM to recover.

Anyone knows about the issue?

**Comment by Sanzo00** [comment]
If you dont specify the number of jobs, `make -j` will create an infinite number of jobs when compile the code, which may exceed the memory limit, and you can try to use `make -j8` to reduce the number of jobs.

**Comment by Steamgjk** [comment]
Thanks. @Sanzo00 
It is really this case. My VM has 8 cores, and after I specified make -j4, I can successfully compile it.
For the previous failure, I think it may be related to resource insufficiency, so reducing parallel jobs can address it. (Maybe should add a reminder note in the ReadMe.md

<img width="580" alt="图片" src="https://user-images.githubusercontent.com/7100589/156030649-7c57f430-f4ca-4f5d-bfb7-c784107e5e53.png">
