### ISSUE TITLE
How to add new code to Galois and modify the Makefile

### ISSUE THREAD

**Issue by Steamgjk** [IntelligentSoftwareSystems/Galois#396]
I am trying to add some new code into Galois. More specifcially, I create a class, which includes a .h and a .cpp file. I put the .h file under libdist/include/galois and put the .cpp file under libdist/include/src

<img width="300" alt="图片" src="https://user-images.githubusercontent.com/7100589/156905551-7536fc5e-7fa4-44c8-bab7-49c6ebd8b4db.png">

My question is: If I want to compile this class into the project and construct such objects in the applications (e.g. sssp_pull.cpp), which make/cmake files should I  modify?( I checked the Makefile, and it seems very complex, I think it may be generated by automatic script, so I am wondering which files are the fundamental files to modify)

**Comment by l-hoang** [comment]
You should add the new cpp file to the CMakeLists under libdist.

**Comment by Steamgjk** [comment]
<img width="350" alt="图片" src="https://user-images.githubusercontent.com/7100589/158033422-9438a260-cb6f-42f8-892b-12b780c7845a.png">

Added here, and regenerate the makefile (i.e. clean the old makefiles and dep folders and then create new ones)
