### ISSUE TITLE
Barriers test crashes with recent versions of clang

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#69]

**Comment by ddn0** [comment]
I narrowed down this issue to the following test case from the original failure reiniting a CountingBarrier (`std::vector<Padded<int>>` is the reduced form of a CountingBarrier):

```cpp
#include <vector>
#include <stdio.h>

// Store an item with padding
template <typename T>
struct Padded {
  alignas(64) T data;
  char buffer[64 - (sizeof(T) % 64)];
};

int main(int argc, char** argv) {
  std::vector<Padded<int>> aVec;
  printf("%p %ld\n", &aVec[0], sizeof(Padded<int>));
  aVec.resize(1);
  printf("%p\n", &aVec[0]);
  aVec.resize(2); // <-- dies here
  printf("%p\n", &aVec[0]);
}
```

And the writeup here, 
- https://stackoverflow.com/questions/52000359/clang-c17-stdvector-over-aligned-types-copy-of-elements-sigsegv-when-compile

mirrors my experience.

Setting `-std=c++17` is one possible solution. I'm not sure of a more elegant work-around.

**Comment by insertinterestingnamehere** [comment]
Yah, that's an interesting one. It's probably because vector does a plain new and until c++17, new doesn't respect nonstandard alignments. Switching standards would work around the fact that all our `new` allocations don't respect the nonstandard alignments for things tagged with `GALOIS_ATTRIBUTE_ALIGN_CACHE_LINE` as well. An alternative workaround isn't obvious to me either. I know (at least as of recently) that the Galois headers are usable from within C++17 code, so migrating should hopefully not be a huge pain. It also appears that all the compilers we currently support also at least support the `-std=c++17` flag (or `std=c++1z` for clang 4).

**Comment by insertinterestingnamehere** [comment]
Closing this since we now use C++17. @ddn0 Thanks for pointing out the fix!
