### ISSUE TITLE
Poor Scaling of Exceptions Workaround

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#72]
This is a companion issue to https://github.com/IntelligentSoftwareSystems/Galois/issues/71 focused on the question "what do we do now?" We need a short term solution since getting exceptions to scale in parallel contexts will likely require some long term work on upstream projects.

There are a few things that would be nice to achieve:
- Not relying on a custom toolchain
- Not killing performance of apps with moderate contention
- Resolve the crashes in the gmetis and torus apps
- Not breaking user code in conter-intuitive ways
- Not poluting the user interface with additional options
- Not forcing users to worry about another configuration setting

Here are a few plausible options and where they stand:
1. Sticking with longjump exclusively provides good performance, but relies on the currently undocumented assumption that operators that use conflict detection do not construct any objects that require nontrivial destruction before reaching their failsafe point. If we stick with this in the long run we should probably document this limitation. We already warn people not to modify data till after the failsafe point, so this isn't much more of a constraint than that. Switching off setjmp/longjmp based aborts also fixed our gmetis and torus apps. That said, it's possible that the runtime locks for exceptions are just hiding some other bug in those cases, so more investigation is needed to see what's going on there. This is what we'd been doing up until we realized the crashes in torus and gmetis were connected to this. If we commit to this option we should at least document the additional limitations on operators.
2. Switching to exceptions entirely has severe performance implications for some apps. It does avoid adding additional constraints on the style of code the user writes though. It also fixes the crashes in gmetis and torus. It also avoids any user interface issues.
3. Modifying the Galois API to no longer rely on exceptions for locking/control flow. It's not currently clear what this would look like, but maybe we could modify our API to make operator aborts something that doesn't have to involve unwinding the stack at all.
4. Use exceptions in the CI tests and nowhere else. This requires no user options and very little additional work from us right now, but it could result in unexpected memory leaks or crashes in user code that uses the current implementation of conflict detection. It also only hides the issue in gmetis and torus and introduces a disparity in our testing environment that could hide other bugs as well.
5. Allow switching between setjmp/longjmp based aborts and exception based aborts via a preprocessor flag. This avoids directly polluting the user interface, but still requires users to make a decision about which exception style is better suited to their application. If we get the exception scaling issues fully fixed upstream then the build option can be silently ignored later without any API changes. We can avoid major performance penalties by allowing demo applications that need setjmp/longjmp to opt into that abort mechanism in their build configs.
6. Allow switching between abort implementations via a template argument flag. This directly pollutes the user API with something that is arguable an implementation choice, but it makes sense if we actually intend setjmp/longjmp to be permanent distinct options for aborts.

Thus far I'm partial to option 5 (see https://github.com/IntelligentSoftwareSystems/Galois/pull/68), but my opinion isn't the only one that matters. We also need to measure to see exactly what kinds of performance tradeoffs are in play here. If exceptions kill performance in every case where we use termination detection then options 1 and 3 are probably better approaches.

**Comment by amberhassaan** [comment]
Meta comment first: It appears to me (from far away) that this discussion is taking place in 2 or 3 places. Can we consolidate in one place please? 

I favor option 5. Reasons: 
  -- Like I said, we had to revive setjump/longjump to fix poor scaling. 
  -- It's not clear if & when the issue will get fixed in abi_runtime. Asking people to install a custom piece can be asking too much. I'd find it annoying that after I checkout Galois, I need to install a custom tool-chain. 
  -- Until the issue is fixed in abi runtime, we can restrict the rules on what's allowed in the operator. If creating non-stack-resident objects are inevitable, we can allow the usercode to register undo operations as callbacks that get invoked on abort. That's something I did for ordered runtime. Although that does require adding to the user API.

**Comment by insertinterestingnamehere** [comment]
The original idea in keeping things separate was to divide the discussion into "what can we do assuming things aren't fixed upstream" and "how can we get things fixed upstream." You're right that that division isn't really working though. I'll migrate the content in this issue over to https://github.com/IntelligentSoftwareSystems/Galois/issues/71.

**Comment by insertinterestingnamehere** [comment]
Closed so we can continue in https://github.com/IntelligentSoftwareSystems/Galois/issues/71
