### ISSUE TITLE
Galois does not compile on Intel compiler 19 (icpc)

### ISSUE THREAD

**Issue by l-hoang** [IntelligentSoftwareSystems/Galois#74]
There appears to be an issue with template argument expansion:

Galois/libgalois/include/galois/gtuple.h(77): error: pack expansion does not make use of any argument packs
    using append = integer_seq<T, Is..., I>;
                                    ^
          detected during instantiation of class "galois::integer_seq<T, Is...> [with T=int, Is=<>]" at line 104

**Comment by insertinterestingnamehere** [comment]
Why do we even have that header? It seems to be providing a bunch of standard C++11 stuff that we can now just get from the standard library. Tuples are hard to get right and the compiler likely already supports the implementation in the standard library.

**Comment by insertinterestingnamehere** [comment]
Okay, slight revision to the last comment. Looking at this more carefully, that header does provide several things beyond what's standardized, but we don't need our own integer_sequence/make_integer_sequence. These are standard in C++14 and we require that now.

**Comment by l-hoang** [comment]
I guess it's best if we remove the things that are standard from the file then?

**Comment by insertinterestingnamehere** [comment]
Yep. They are probably used somewhere so we'll have to swap in the standard versions, but other than that things *should* just work. We could run into trouble if icpc doesn't support the standard version either, but hopefully Intel will have tested that.

**Comment by l-hoang** [comment]
Cool. I can take a look at this for the release.

**Comment by ddn0** [comment]
Fixed by #151
