### ISSUE TITLE
Constant warnings when compiling

### ISSUE THREAD

**Issue by bozhiyou** [IntelligentSoftwareSystems/Galois#75]
With gcc 8.1, warnings as follows always occur when compiling the code.

> In file included from /opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/mpl/aux_/na_assert.hpp:2
3,
                 from /opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/mpl/arg.hpp:25,
                 from /opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/mpl/placeholders.hpp:24,
                 from /opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/iterator/iterator_catego
ries.hpp:16,
                 from /opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/iterator/iterator_facade
.hpp:13,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/FixedSizeRing.h:27,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/worklists/PerThreadChunk.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/worklists/WorkList.h:25,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Traits.h:24,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/runtime/Executor_OnEach.h:24,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Bag.h:24,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/runtime/Executor_Deterministic.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Loops.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Galois.h:23,
                 from /h1/byou/Workspace/GaloisCpp/lonestar/connectedcomponents/ConnectedComponents.cpp:20:
/opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/mpl/assert.hpp:188:21: warning: unnecessary pa
rentheses in declaration of ‘assert_arg’ [-Wparentheses]
 failed ************ (Pred::************
                     ^
/opt/apps/ossw/libraries/boost/boost-1.67.0/c7/gcc-8.1/include/boost/mpl/assert.hpp:193:21: warning: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Wparentheses]
 failed ************ (boost::mpl::not_<Pred>::************

> In file included from /h1/byou/Workspace/GaloisCpp/libllvm/include/llvm/Support/CommandLine.h:25,
                 from /h1/byou/Workspace/GaloisCpp/lonestar/connectedcomponents/ConnectedComponents.cpp:30:
/h1/byou/Workspace/GaloisCpp/libllvm/include/llvm/ADT/SmallVector.h: In instantiation of ‘static void llvm::SmallVectorTemplateBase<T, true>::uninitialized_copy(T1*, T1*, T2*) [with T1 = const std::pair<const char*, std::pair<int, const char*> >; T2 = std::pair<const char*, std::pair<int, const char*> >; T = std::pair<const char*, std::pair<int, const char*> >]’:
/h1/byou/Workspace/GaloisCpp/libllvm/include/llvm/ADT/SmallVector.h:636:3:   required from ‘const llvm::SmallVectorImpl<T>& llvm::SmallVectorImpl<T>::operator=(const llvm::SmallVectorImpl<T>&) [with T = std::pair<const char*, std::pair<int, const char*> >]’
/h1/byou/Workspace/GaloisCpp/libllvm/include/llvm/ADT/SmallVector.h:693:36:   required from ‘llvm::SmallVector<T, N>::SmallVector(const llvm::SmallVector<T, N>&) [with T = std::pair<const char*, std::pair<int, const char*> >; unsigned int N = 4]’
/h1/byou/Workspace/GaloisCpp/libllvm/include/llvm/Support/CommandLine.h:444:7:   required from ‘llvm::cl::ValuesClass<DataType> llvm::cl::values(const char*, DataType, const char*, ...) [with DataType = int]’
/h1/byou/Workspace/GaloisCpp/lonestar/connectedcomponents/ConnectedComponents.cpp:82:21:   required from here
/h1/byou/Workspace/GaloisCpp/libllvm/include/llvm/ADT/SmallVector.h:244:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct std::pair<const char*, std::pair<int, const char*> >’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(Dest, I, (E - I) * sizeof(T));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/apps/ossw/applications/gcc/gcc-8.1/c7/include/c++/8.1.0/utility:70,
                 from /opt/apps/ossw/applications/gcc/gcc-8.1/c7/include/c++/8.1.0/tuple:38,
                 from /opt/apps/ossw/applications/gcc/gcc-8.1/c7/include/c++/8.1.0/mutex:38,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/substrate/SimpleLock.h:27,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/substrate/PaddedLock.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/PriorityQueue.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/gstl.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Bag.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/runtime/Executor_Deterministic.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Loops.h:23,
                 from /h1/byou/Workspace/GaloisCpp/libgalois/include/galois/Galois.h:23,
                 from /h1/byou/Workspace/GaloisCpp/lonestar/connectedcomponents/ConnectedComponents.cpp:20:
/opt/apps/ossw/applications/gcc/gcc-8.1/c7/include/c++/8.1.0/bits/stl_pair.h:198:12: note: ‘struct std::pair<const char*, std::pair<int, const char*> >’ declared here
     struct pair
            ^~~~

**Comment by insertinterestingnamehere** [comment]
It'd be great to get the warnings down. The unnecessary parenthesis warning pass in gcc 8.1 is buggy so we may have to just disable that warning everywhere. I ran into that a while ago and reported it in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85775. The memcpy warning can probably be fixed by updating our llvm headers.

**Comment by insertinterestingnamehere** [comment]
If we can get to a point where we compile without warnings we should then add the `-werror` flag to make sure no new warnings are introduced.

**Comment by ddn0** [comment]
@insertinterestingnamehere and co feel free to jump on the related change https://github.com/KatanaGraph/katana/pull/6

More work probably needs to be done to support icc and older gcc's though that is probably out of scope for Katana.

**Comment by insertinterestingnamehere** [comment]
Awesome! Thanks for that!

**Comment by ddn0** [comment]
We now `-Werror` for gcc and clang. There are quite a few warnings with CUDA sources but if someone wants to take that on, it is probably separate from this issue.
