### ISSUE TITLE
libllvm too old to support option categorization

### ISSUE THREAD

**Issue by bozhiyou** [IntelligentSoftwareSystems/Galois#77]
The latest (or some earlier versions) llvm commandline parsing library supports [option categorization](https://llvm.org/docs/CommandLine.html#grouping-options-into-categories), which makes the help information (output of -help option) more systematic and pretty. For example, we can categorize the common options like -runs, -t, etc. into a group, and other application- or even algorithm-specific options like -edgeTileSize into other groups. Current libllvm is too old to support this.

**Comment by insertinterestingnamehere** [comment]
Just to add on to this, the fix is to update the LLVM headers we've copied into our repo. Note: we don't need or want all of LLVM, just the stuff for command line argument handling (and possibly smallvector?).

**Comment by yishanlu** [comment]
I remember that we switched to boost small vector for customizable memory allocators. Need to check MorphGraph for this...

**Comment by insertinterestingnamehere** [comment]
A quick search actually doesn't turn up any uses of small_vector in the non-experimental stuff. The betweenness centrality app includes the header but doesn't actually use it. It sounds like we're good to go without small_vector.

**Comment by ddn0** [comment]
I got bored so here's one way to remove libllvm:

https://github.com/KatanaGraph/katana/pull/41

Over at Katana we presume that users know how to setup cmake to point to the right places for an installed library. I don't know if that is the assumption here. Do you think it would be better to put in a submodule to llvm here?

**Comment by insertinterestingnamehere** [comment]
My assumption has been that they can get what they need via find_package. We already expect people to do that for boost. Picking LLVM up that way should already work on the servers we use for development and performance testing, but I'll have to double-check that.
