### ISSUE TITLE
Add Adaptive OBIM Worklist

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#78]
In a recent SC paper (https://www.cs.tau.ac.il/~mad/publications/sc2019-cps.pdf) @serifyesil put together an adaptive version of OBIM available at https://github.com/serifyesil/pmod. It would be great if we could get a version of this new worklist up and running against the newer version of Galois.

**Comment by insertinterestingnamehere** [comment]
Note: Since Galois has changed license, we need explicit permission to release the updated code under the BSD license instead of the old UT Research License. @serifyesil, is the new licensing okay with you?

**Comment by insertinterestingnamehere** [comment]
@serifyesil? Can we adapt your code for the newer Galois release and release it under the BSD license instead of the old license?

**Comment by serifyesil** [comment]
BSD license is okay for me. Feel free to use the code.

**Comment by insertinterestingnamehere** [comment]
Thank you!

**Comment by insertinterestingnamehere** [comment]
I've been working on getting this code working with the current version of Galois, but given that it's a new feature, I'm deferring that until after the release is finalized.
