### ISSUE TITLE
Config header

### ISSUE THREAD

**Issue by yishanlu** [IntelligentSoftwareSystems/Galois#80]
Currently if other projects want to use Galois as a library and write their own Galois app, they have to let Galois pass its CXX flags through CMake options.

It would be better if these options can be generated as a Galois config header, which is automatically included by Galois headers. This way other projects can be decoupled from this tangling of CMake options.

**Comment by insertinterestingnamehere** [comment]
Actually this is a duplicate of https://github.com/IntelligentSoftwareSystems/Galois/issues/45. Closing.
