### ISSUE TITLE
SPRoute

### ISSUE THREAD

**Issue by Michael-JY-He** [IntelligentSoftwareSystems/Galois#86]
1. Clean up code. Remove warnings.
2. Prepare a small input for testing. Large input files.
3. Webpage.
4. Move to lonestar/EDA.

**Comment by Michael-JY-He** [comment]
I thought I need to finish the webpage before closing lol?

**Comment by insertinterestingnamehere** [comment]
Good point. Let's keep this open until the webpage is done too.
