### ISSUE TITLE
Pangolin

### ISSUE THREAD

**Issue by chenxuhao** [IntelligentSoftwareSystems/Galois#87]
1. Clean up code.
2. Prepare a small input for testing.
3. Webpage.

**Comment by roshandathathri** [comment]
Web page is not an action item here. If 1 and 2 are done, close this issue.

**Comment by insertinterestingnamehere** [comment]
I think we still need tests here. @chenxuhao can you confirm?

**Comment by roshandathathri** [comment]
Please put mining apps in two separate folders:
lonestar/mining/cpu
lonestar/mining/gpu

**Comment by chenxuhao** [comment]
> I think we still need tests here. @chenxuhao can you confirm?

I added the tests. You said in slack that you would help me to put the test data to the right place, remember?

**Comment by insertinterestingnamehere** [comment]
Got it. Thanks for the clarification. I got confused by the commented out tests. It sounds like we now need to uncomment the tests, move the input data to the tarball download (https://github.com/IntelligentSoftwareSystems/Galois/issues/143), and then confirm that the tests actually pass in all the environments we support.

**Comment by chenxuhao** [comment]
> Got it. Thanks for the clarification. I got confused by the commented out tests. It sounds like we now need to uncomment the tests, move the input data to the tarball download (#143), and then confirm that the tests actually pass in all the environments we support.

right.
