### ISSUE TITLE
MPI_Finalize() not executed in bfs_push application (distributed version)

### ISSUE THREAD

**Issue by AmadeusChan** [IntelligentSoftwareSystems/Galois#9]
Hi there, 

When I run the distributed bfs_push application(MPI: openMPI 3.0.1a1), I get some runtime error which suggests that the process may exit without calling "MPI_Finalize". And I find out that the "MPI_Finalize" operation is located in the destructor function of NetworkInterfaceBuffered. It seems that the destructor of "net", an object of "NetworkInterfaceBuffered" class in main(), is never executed, and as a result, the process will exit without calling "MPI_Finalize".

The runtime error I met is:
```
--------------------------------------------------------------------------
mpirun has exited due to process rank 0 with PID 0 on
node cn662 exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command line.
--------------------------------------------------------------------------

```

**Comment by l-hoang** [comment]
Hello.

Yes, it seems as though the destructor for the Network Interface is not getting called. Thanks for letting us know. I will take a look at this and have a fix for you soon.

**Comment by l-hoang** [comment]
Hello.

I've pushed some changes into the master branch that should have fixed this problem. I'm closing the issue for now; if this continues to occur, please reopen the issue, and I will get back to you.

**Comment by l-hoang** [comment]
Hello.

The change I made to resolve this issue is causing non-deterministic hanging of the program. I've reverted it for the time being and am reopening this issue until we figure out what is going on.

**Comment by l-hoang** [comment]
Hello.

I finally got around to resolving the issue; MPI is now finalized at the end of execution with no non-deterministic hanging unlike the first time I tried to fix this.

If these issues continue to occur, please let us know.
