### ISSUE TITLE
Remove dependency on LLVM in Dist Galois

### ISSUE THREAD

**Issue by insertinterestingnamehere** [IntelligentSoftwareSystems/Galois#91]
Dist Galois relies on our vendored copy of libllvm. If the actual llvm headers from a later version are installed, it currently fails. Updating Galois to no longer vendor libllvm is a good fix in general and will fix the build error. On the other hand, things that can be installed as libraries should not assume they have control over the end-user's command line argument handling. If the default options are needed in every distributed app, they should be moved to something like the current liblonestar which takes care of common setup and configuration needed for all the lonestar apps.

**Comment by insertinterestingnamehere** [comment]
https://circleci.com/gh/IntelligentSoftwareSystems/Galois/4549 is an example of a recent failed build. That's just the current CentOS clang/libc++ build with dist galois enabled.

**Comment by roshandathathri** [comment]
Whether we have our own libllvm, use llvm as a submodule, or depend on installed llvm, that's a different issue. In all of our libraries, we should not be using command-line arguments (this allows third-party code to use our libraries more easily). The library options, if any, should be exposed through the library's class/function interface. The apps can then use command-line arguments to set the options through the library's interface.

**Comment by roshandathathri** [comment]
In addition, it would be good if all our libraries have a consistent "options" interface.

**Comment by ddn0** [comment]
Given that https://github.com/IntelligentSoftwareSystems/Galois/pull/104 should happen soon, the remaining issue is to remove the command line parsing from dist galois.

**Comment by l-hoang** [comment]
Done a few days back.
