### ISSUE TITLE
Refactor experimental code

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#94]
We should probably rethink `USE_EXP`. Once we support importing (library) targets, most of the experimental apps can be moved to a separate repo.

For the experimental library code, I propose we audit it with an aim to either promote it to non-experimental or to delete it.

Example: https://github.com/IntelligentSoftwareSystems/Galois/pull/88

**Comment by ddn0** [comment]
```
ddn@spork:katana$ find . -name experimental
./external/cub/experimental
./scripts/experimental
./lonestar/experimental
```
I understand that we still need to keep `lonestar/experimental` while people commit their work in progress. We also have experimental scripts. Can we delete these?

**Comment by roshandathathri** [comment]
> We also have experimental scripts. Can we delete these?

No, we need the experimental scripts. They include scripts we use to run distributed codes on various clusters.



> ./external/cub/experimental

This is in the cub repo I'm assuming, so we have to let it be.

**Comment by ddn0** [comment]
> No, we need the experimental scripts. They include scripts we use to run distributed codes on various clusters.

Then I propose that they are moved out of a directory called `experimental`; there is also ` abelian_log_parser_deprecated.py`? A directory called `older`, etc.

In general, it would be nice that anything specific to ISS (i.e., the research group) to be refactored to be of general utility for people outside of ISS or just moved to a separate repo.
