### ISSUE TITLE
Use size_t in test

### ISSUE THREAD

**Issue by ddn0** [IntelligentSoftwareSystems/Galois#95]
Anything that ever represents a "collection size" should always be size_t, but I suspect this patch is intended to  make the test match what the data structure does to remove a warning, so we can switch everything over to size_t later.

_Originally posted by @insertinterestingnamehere in https://github.com/IntelligentSoftwareSystems/Galois/pull/88_

**Comment by insertinterestingnamehere** [comment]
I'll try to look at this again once we're closer to finalizing the release. Many of the cases where we currently use int are probably technically wrong.

**Comment by insertinterestingnamehere** [comment]
Fixing integer types for the whole repo will be a very large refactor, so I'm tentatively going to remove this from the current release milestone.

**Comment by ddn0** [comment]
If it is going to be a huge refactor, maybe close this ticket altogether? Or rescope it to something that is more modest? For instance, I think with our new warning configuration, if we at least are clear in the `size_t` vs non-`size_t` distinction in the library data structures and routines, this should propagate to applications naturally.

**Comment by insertinterestingnamehere** [comment]
Good idea, just fixing this in libgalois is a much more attainable goal here.

**Comment by insertinterestingnamehere** [comment]
Related question: our current LC_CSR_Graph type uses uint32_t as its node id type. Why? Is there some kind of performance difference? This limits that graph type to holding at most 4294967295 nodes before overflow occurs. Are all of our graphs really that small?

For C++ containers my rule of thumb is that anything that is at all index-like needs to be `size_t`. Is there any reason not to change to size_t for node ids everywhere?

**Comment by ddn0** [comment]
It does have a measurable difference but measured in % and not X. There is a FileGraph V2 that supports 64-bit offsets but it doesn't seem to be widely used.

Over at Katana, we considered just switching to uint64_t but the partitioning code requires some refactoring to support this, but it is on the roadmap somewhere.

cc @roshandathathri

**Comment by l-hoang** [comment]
At least for distributed execution uint64 has more comm. overhead than uint32 by virtue of being double the size.

Not sure about shared memory.

**Comment by roshandathathri** [comment]
> our current LC_CSR_Graph type uses uint32_t as its node id type. Why? Is there some kind of performance difference? 

Yes, I expect to see performance difference - measured in %, not X as Donald said.

> This limits that graph type to holding at most 4294967295 nodes before overflow occurs. Are all of our graphs really that small?

Graphs that fit on a single machine typically, yes. However, once we consider Optane or other large memory machines, it won't be.

> At least for distributed execution uint64 has more comm. overhead than uint32 by virtue of being double the size.

Not really. We communicate a bitvector typically with the values, instead of IDs/local-offsets. IDs/local-offsets are sent instead of bitvector only if their size is small, so changing them from 32-bit to 64-bit will not change communication performance by much. Also, also it's unlikely that local-offsets need to be change from 32-bit to 64-bit because the offset is for the vertices shared between two devices.

**Comment by l-hoang** [comment]
> Not really. We communicate a bitvector typically with the values, instead of IDs/local-offsets. IDs/local-offsets are sent instead of bitvector only if their size is small, so changing them from 32-bit to 64-bit will not change communication performance by much. Also, also it's unlikely that local-offsets need to be change from 32-bit to 64-bit because the offset is for the vertices shared between two devices.

Makes sense.
